### ISSUE TITLE
Azure AD Authentication Fails

### ISSUE THREAD

**Issue by Jack64** [alexellis/openfaas-oidc-plugin-pkg#1] opened 2019-08-22 16:24 UTC
## Description

Hi,

I realize this is in alpha stage, but...

I was trying to configure the oidc plugin with Azure AD and all goes well up until the OAUTH2 token is requested by the oidc plugin, which triggers the following error message:

```json: cannot unmarshal string into Go struct field accessToken.expires_in of type int```

I used the oauth2 debugger to check the JSON returned by Azure and in fact they return all strings in these fields:

```{"token_type":"Bearer","expires_in":"3600","ext_expires_in":"3600","expires_on":"1566493809","access_token":"..."}```

Can you please make adjustments in order for the plugin to work with Azure AD as well?

Thanks for all your work on OpenFaaS!

#### Settings

Image: alexellis/oidc-plugin-dist:0.2.0
Env vars:
```
    Environment:
      client_id:                     <REDACTED_AZURE_AD_APPLICATION_ID>
      client_secret:                 <REDACTED_AZURE_AD_SP_PASSWORD>
      cookie_domain:                 .openfaas.<REDACTED_URL>
      base_host:                     https://oauth.openfaas.<REDACTED_URL>
      port:                          8080
      authorize_url:                 https://login.microsoftonline.com/<REDACTED_TENANT_ID>/oauth2/authorize
      welcome_page_url:              https://gw.openfaas.<REDACTED_URL>
      public_key_path:               
      audience:                      https://gw.openfaas.<REDACTED_URL>
      token_url:                     https://login.microsoftonline.com/<REDACTED_TENANT_ID>/oauth2/token
      scopes:                        openid profile email
      jwks_url:                      https://login.microsoftonline.com/<REDACTED_TENANT_ID>/discovery/keys?appid=<REDACTED_AZURE_AD_APPLICATION_ID>
      insecure_tls:                  false
```

**Comment by alexellis** [comment] 2019-11-30 21:49
Thanks @Jack64 for the message. Can you email alex@openfaas.com with more about your use-case?

**Comment by alexellis** [comment] 2020-03-23 12:07
@Jack64 are you able to follow-up? I'm still waiting from November :-)

Related to this, I've been using Azure AD and can authenticate via the UI, there appears to be a 307 redirect that Intility also ran into when using the CLI and code-flow.

I can't reproduce the error you mention though. Is there anything special in your setup? When do you see it?

**Comment by Jack64** [comment] 2020-03-23 12:14
Hey @alexellis . Wow somehow I didn't see this reply. I experimented with this and then rolled back from Azure AD to basic auth when I got stuck with this one and haven't touched it since. It also appears that since then you've made this module a commercial add-on so I suppose it'd be hard to check if this is still happening without a license.

**Comment by alexellis** [comment] 2020-03-23 12:49
You're entitled to apply for a free trial :-)

Using the code flow, and the token from the browser this works via the CLI also. I can't manage to reproduce the issue you were running into though, I added additional logging to check for it also.

If you'd be open to trying it out again, you can get a trial by emailing sales@openfaas.com.

Alex

**Comment by alexellis** [comment] 2020-03-23 20:48
Closing as this cannot be reproduced.

**Closed** 2020-03-23 20:48 UTC
